name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ["self-hosted", "Linux", "X64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials Upload files to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload files to S3
        run: |
          aws s3 sync \
            --region us-east-1 \
            frontend/build \
            s3://naegiftdid \
            --delete
