name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ["self-hosted", "Linux", "X64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: .env setting
        run: |
          echo "REACT_APP_AWS=${{ secrets.REACT_APP_AWS }}" >> .env
          echo "REACT_APP_MARKET_ADDRESS=${{ secrets.REACT_APP_MARKET_ADDRESS }}" >> .env
          echo "REACT_APP_PROXY_CONTRACT=${{ secrets.REACT_APP_PROXY_CONTRACT }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
