name: deploy
on:
  push:
    branches: [main]
env:
  CI: false
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Checkout source code.
        uses: actions/checkout@main
        env:
          REACT_APP_AWS: ${{ secrets.REACT_APP_AWS }}
          REACT_APP_TARGET_CHAINID: ${{ secrets.REACT_APP_TARGET_CHAINID }}
          REACT_APP_MARKET_ADDRESS: ${{ secrets.REACT_APP_MARKET_ADDRESS }}
          REACT_APP_PROXY_CONTRACT: ${{ secrets.REACT_APP_PROXY_CONTRACT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install npm packages
        working-directory: ./frontend
        run: npm install --legacy-peer-deps
      - name: Build
        working-directory: ./frontend
        run: npm run build
      - name: Sync Bucket
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 sync frontend/build s3://naegiftdid --delete
